export const APP_TOGGLE_CHANNEL_CREATE = 'APP_TOGGLE_CHANNEL_CREATE';
export const APP_CHANNELS_LOADING = 'APP_CHANNELS_LOADING';
export const APP_CHANNEL_CREATING = 'APP_CHANNEL_CREATING';
export const APP_CHANNEL_UPDATING = 'APP_CHANNEL_UPDATING';
export const APP_CHANNEL_CHANGE = 'APP_CHANNELS_CHANGE';

export const APP_USER_LOGINNING = 'APP_USER_LOGINNING';
export const APP_USER_CHANGING_NAME = 'APP_USER_CHANGING_NAME';

export const APP_MESSAGES_LOADING = 'APP_MESSAGES_LOADING';
export const APP_MESSAGE_SENDING = 'APP_MESSAGE_SENDING';
export const APP_MESSAGE_UPDATING = 'APP_MESSAGE_UPDATING';
