export const EDIT_CHANNEL = 'EDIT_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';

export const CHANNELS_FETCH_SUCCESS = 'CHANNELS_FETCH_SUCCESS';
export const CHANNELS_FETCH_FAILURE = 'CHANNELS_FETCH_FAILURE';

export const CHANNELS_CREATE_SUCCESS = 'CHANNELS_CREATE_SUCCESS';
export const CHANNELS_CREATE_FAILURE = 'CHANNELS_CREATE_FAILURE';


