export const CHANNELS_FETCH_SUCCESS = 'CHANNELS_FETCH_SUCCESS';
export const CHANNELS_UPDATE_SUCCESS = 'CHANNELS_UPDATE_SUCCESS';
export const CHANNEL_CREATE_SUCCESS = 'CHANNELS_CREATE_SUCCESS';
export const CHANNEL_UPDATE_SUCCESS = 'CHANNEL_UPDATE_SUCCESS';
