export const USER_LOGIN_SUCCESS = 'EDIT_USER_NAME';
export const USER_LOGIN_FAILURE = 'CHANNELS_FETCH_FAILURE';

export const USER_LOGOUT = 'CHANNELS_FETCH_FAILURE';

export const USER_EDIT_NAME = 'USER_EDIT_NAME';
export const USER_CHANGE_AVATAR = 'USER_EDIT_NAME';
