export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_EDIT_NAME = 'USER_EDIT_NAME';
export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR';
